In [5]:
import pandas as pd

In [20]:
df = pd.read_csv('News.csv', engine = 'python', on_bad_lines= 'skip')

In [10]:
df.head()

,Unnamed: 0,title,text,subject,date,class
0,0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0

In [21]:
df.isnull().sum()

Unnamed: 0     0
title          0
text           0
subject       21
date          21
class          0
dtype: int64

In [22]:
## get the independent features
x = df.drop('class' ,axis = 1)

In [23]:
y = df['class']

In [24]:
## check whather dataset is balanced or not
y.value_counts()

class
0    23502
1    19141
Name: count, dtype: int64

In [25]:
import tensorflow as tf

In [26]:
tf.__version__

'2.20.0'

In [27]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Bidirectional

In [28]:
#vocabulary size
voc_size = 5000

In [29]:
messages = x.copy()

In [30]:
messages

,Unnamed: 0,title,text,subject,date
0,0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"
...,...,...,...,...,...
42638,19136,Tale of two cities: Kurdish vote lays bare pol...,"SULAIMANIYA, Iraq (Reuters) - Some Kurdish lea...",worldnews,"September 25, 2017"
42639,19137,French unions block fuel depots in protest aga...,PARIS (Reuters) - French trade unionists block...,worldnews,"September 25, 2017"
42640,19138,British police arrest seventh man over bomb at...,LONDON (Reuters) - British police made a new a...,worldnews,"September 25, 2017"
42641,19139,Malaysia's dissent on Myanmar statement reveal...,KUALA LUMPUR (Reuters) - Dissent surfaced agai...,worldnews,"September 25, 2017"
42642,19140,"Trump slaps travel restrictions on N.Korea, Ve...",WASHINGTON (Reuters) - President Donald Trump ...,worldnews,"September 25, 2017"

In [31]:
import nltk

In [32]:
import re
from nltk.corpus import stopwords

In [33]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [41]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus =[]
for i in range(0 ,len(messages)):
  review = re.sub('[^a-zA-Z]',' ',messages['title'][i])
  review = review.lower()
  review = review.split()
  review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
  review = ' '.join(review)
  corpus.append(review)

In [42]:
corpus

['donald trump send embarrass new year eve messag disturb',
 'drunk brag trump staffer start russian collus investig',
 'sheriff david clark becom internet joke threaten poke peopl eye',
 'trump obsess even obama name code websit imag',
 'pope franci call donald trump christma speech',
 'racist alabama cop brutal black boy handcuff graphic imag',
 'fresh golf cours trump lash fbi deputi director jame comey',
 'trump said insan racist stuff insid oval offic wit back',
 'former cia director slam trump un bulli openli suggest act like dictat tweet',
 'watch brand new pro trump ad featur much kiss make sick',
 'papa john founder retir figur racism bad busi',
 'watch paul ryan told us care struggl famili live blue state',
 'bad news trump mitch mcconnel say repeal obamacar',
 'watch lindsey graham trash media portray trump kooki forget word',
 'heiress disney empir know gop scam us shred tax bill',
 'tone deaf trump congrat rep scalis lose weight almost die',
 'internet brutal mock disney new trump robot hall presid',
 'mueller spokesman f cked donald trump christma',
 'snl hilari mock accus child molest roy moor lose al senat race video',
 'republican senat get drag go robert mueller',
 'heartless rebuk victim trump invit nra xma parti sandi hook anniversari',
 'ky gop state rep commit suicid alleg molest teen girl detail',
 'meghan mccain tweet amaz respons doug jone win deep red alabama',
 'cnn call democrat repres alabama senat first time year',
 'white hous sexist trump slut shame sen kirsten gillibrand video',
 'despic trump suggest femal senat would anyth campaign money tweet',
 'accus child molest senat candid roy moor side putin reagan video',
 'watch fox host call cleans fbi arrest everyon investig trump',
 'liber group troll trump roy moor ralli best possibl way video',
 'jr tri mock al franken resign backfir immedi',
 'break cop final get due walter scott killer sentenc prison detail',
 'watch proof trump unfit servic',
 'trump complet screw middl east peac process anoth wednesday',
 'trump care trump recogn jerusalem today',
 'watch trump support coal ceo upset trump wipe thousand coal mine job',
 'sit gop senat enough donat alabama democrat senat imag',
 'republican nation committe better pedophil democrat u senat',
 'donald trump eat habit could dramat affect wellb safeti',
 'john mccain want anoth twitter follow plan backfir miser tweet',
 'sarah huckabe sander tweet attack fbi age well',
 'fbi agent destroy donald trump attack agenc jame comey',
 'ghost wit flip hilari snl skit take trump privat holiday hell video',
 'leak email prove trump offici awar russia thrown usa elect trump',
 'trump admit knew flynn lie fbi ask comey drop investig',
 'watch awesom mashup michael flynn lead lock chant goe court video',
 'white hous panic know flynn go take',
 'break michael flynn crack testifi mueller trump',
 'trump get epic f ck britain white supremacist retweet',
 'hilari campaign ad show voter avoid scandal elect offici',
 'joe scarborough imagin trump realli lose mind video',
 'sourc confirm robert mueller offic interview jare kushner sever week ago',
 'trump send crazi time tweet wrong account lose sh world leader remark',
 'american elect presid accus rape year old girl',
 'trump biggest kkk fan back love anti muslim tweet morn',
 'trump spent night retweet white supremacist convict crimin',
 'sean hanniti throw stage temper tantrum photo pose imag',
 'democrat give trump big f ck attack insan twitter rant',
 'trump wake scream black peopl hurl racial slur yesterday',
 'trump support object princ harri recent engag terribl reason tweet',
 'honor nativ american code talker trump call elizabeth warren pocahonta video',
 'pro trump group use pictur obama ralli make trump look popular',
 'breitbart editor cnn host song ringo starr prove roy moor pedo video',
 'former obama photograph take troll trump whole new level tweet',
 'back golf vacay trump say done presid ever',
 'two week elect trump still defend accus child molest tax',
 'principl power republican need right remain relev',
 'trump everyth heard say access hollywood tape never happen',
 'cnn blister trump attack bad represent job tweet',
 'sean hanniti get wreck yell time magazin call trump lie',
 'time magazin humili trump lie award',
 'ivanka defend malia obama attack dad fan stop look like baboon',
 'trumpster launch insan conspiraci theori boot john mccain foot',
 'gay gop oper endors doug jone bigot deviant roy moor senat race video',
 'watch retir alabama cop told keep roy moor away high school cheerlead',
 'new york time report actual russian agent congress code name',
 'fox news ban gene simmon life harass staff camera',
 'watch nicol wallac take trump woodsh back pedophil moor',
 'pastor goe full qaeda defend roy moor want teen girl puriti',
 'trump nation secur advis reportedli trash epic',
 'trump favorit news channel tri sooth batter ego get taken cleaner',
 'texa governor broke trump unpreced',
 'conserv christian leader kept sexual assault secret republican lawmak',
 'gop senat caught hot mic trash parti roy moor donald trump video',
 'donald trump destroy countri reput proof',
 'trump got p ssi hand new zealand femal prime minist',
 'chao ensu man accident shoot wife church gun safeti talk',
 'new accus confirm got roy moor ban mall video',
 'roy moor ask peopl snitch media get troll hard tweet',
 'trump admin toss anoth obama rule son even wors douchebag',
 'internet light pentagon accident retweet call trump resign',
 'anti gay gop rep get bust inappropri relat man state offic',
 'time trump mock marco rubio drink water came back haunt',
 'watch corpor ceo shock trump econom advis truth gop tax cut',
 'texa sheriff threaten jail truck owner anti trump sticker screenshot',
 'watch delusion trump fan lash fox host report fact uranium one deal',
 'roy moor support republican lose call extremist',
 'stori trump told press obama air forc one never happen',
 'year old tweet donald trump show us least pervert roy moor',
 'oop trump judici nomine tell congress marriag white hous attorney',
 'trump laugh philippin leader call journalist spi countri journalist routin murder',
 'watch joe biden wreck trump six word hilari',
 'bust leak document prove trump took launder money russian bank',
 'pervert gop state rep corner lobbyist tri forc help rage b ner',
 'roy moor former colleagu knew like date teenag girl',
 'watch christian right founder condemn support nazi sexual misconduct',
 'conserv christian leader defend pedophil gop candid roy moor',
 'trump throw intellig commun bu side putin despit strong evid russian meddl',
 'old mike penc tweet sure uncomfort g maga mean grope',
 'sean hanniti said child molest ok consensu video',
 'newsweek made best cover ever peopl freak',
 'alabama republican defend pedophilia use bibl',
 'gop senat candid turn disgust child molest',
 'senat democrat sneak around behind gop back unravel trump administr',
 'sunday massacr texa bump columbin top ten deadliest us mass shoot',
 'sean hanniti bare spend second last night drub revisit trump victori instead',
 'main voter tell trump go f ck expand medicaid obamacar',
 'watch rick santorum torch trump take respons elector bloodbath',
 'trump seeth humili virginia elect throw ed gillespi bu',
 'resist gave trump huge f ck elect night',
 'trump justic dept realiz prosecut woman laugh stupid drop case entir',
 'trump jr goe full dumba twitter promot wrong day virginia elect',
 'trump openli call third world war video',
 'oop trump agre peopl like treat harshli milk countri',
 'miss texa gave unexpect answer ask trump republican furiou',
 'trump tri make facebook give person info peopl critic',
 'multipl wit confirm pee pee tape real',
 'fox news complet transform safe space fragil snowflakey donald trump',
 'trump tell japanes diplomat never knew mani countri world',
 'latest conserv god answer victim prayer let get shot',
 'univers texa polic kick humili nazi campu could start troubl',
 'russian lawyer drop bomb donald trump jr alleg direct pay play attempt',
 'watch republican lawmak claim forc women babi help economi',
 'someon tri cash antifa jacket twitter field day',
 'senat deliv scath rebuk gop colleagu one safe',
 'remind much nra spent trump wake anoth mass shoot',
 'peopl murder texa mass shoot trump respons classic racist',
 'trump went japan immedi prove know zilch missil work',
 'wall close trump disgrac nation secur advis face indict team mueller',
 'former waterg prosecutor mueller could gag trump russia',
 'gop lawmak link abort economi one bizarr horribl offens rant video',
 'hawaiian perfect sign infuri trump land',
 'trump want suprem court punish lawyer win case administr',
 'hypocrit ivanka trump humili call end sexual harass predat dad japan',
 'pull nfl relat ad papa john get unlik sponsor nazi',
 'mike penc get special gift offic mail everi month probabl burn video',
 'two word gop congressman admit answer constitu',
 'one hero made donald trump panic made twitter celebr detail',
 'sarah huckabe sander shred l time truth twist brilliant',
 'trump energi secretari idea stop sexual assault insan',
 'jeff session oh mean russian contact rememb',
 'alt right white hous report get fool fake tweet report upcom civil war',
 'papa john attack nfl first amend sh tti pizza lose small fortun',
 'trump liter sabotag case nyc terrorist keep mouth shut',
 'reason littl known trump aid danger trump paul manafort',
 'former ambassador accus trump violat constitut everi time diplomat visit',
 'trump throw jare kushner bu mueller indict',
 'russian fool dumbass conserv meme hillari fistfight jesu',
 'chuck schumer nuke trump blame terrorist attack',
 'watch gop senat almost knock american flag dodg indict question video',
 'watch trump chief staff john kelli admit think anyth wrong slaveri',
 'legal commun school trump lawyer claim collus crime',
 'watch hanniti lose sh refer hillari presid clinton unhing rant',
 'seth meyer sum monday event perfectli video',
 'hanniti tweet like knife back trump',
 'sh tti birthday must ivanka trump',
 'guilti hell paul manafort rick gate enter guilti plea russian collus scandal tweet video',
 'fox news consid news everyon els cover indict trump camp manag',
 'racist head explod find white white crime higher',
 'mccain best laugh year ask donald trump',
 'attempt trump pardon anyon indict mueller could backfir big way',
 'need trump move fire mueller shut russia probe',
 'number state insur liter say obamacar trainwreck trump fault',
 'hillari hilari rib fox host insan obsess impeach video',
 'internet wreck tomi lahren halloween costum violat u flag code',
 'someth trump panic mueller investig close',
 'hillari clinton total rub indict rumor trump big orang face screenshot',
 'twitter ban major trump alli threaten journalist screenshot',
 'look way irrit trump tip imag',
 'break first charg file mueller russia investig',
 'trump puerto rico contract two man energi compani corrupt f ck',
 'watch former white hous offici suggest hanniti hillari clinton execut',
 'trump close offic coordin russia sanction',
 'yet anoth asshol ram bunch protest car video',
 'judg bar mom see babi year unpaid fee resign',
 'trump got ban place propos melania',
 'john lewi perfect birthday messag hillari trump furiou tweet',
 'milo yiannopoulo tell aussi vote marriag equal week gay wed',
 'trump ice thug stop ambul take year old girl cerebr palsi surgeri',
 'alt right trump lover lose sh kill dad call nazi',
 'watch amazingli awar compani creat brilliant way document trump danger tweet',
 'melania trump hit seriou side eye tell black kid respect',
 'trump wet pant bob corker corker alert white hous daycar staff',
 'gop senat candid say kid murder sandi hook god angri',
 'watch john mccain mock presid bone spur draft defer',
 'soldier widow final speak made cri even trump call liar immedi',
 'nurs textbook recal apolog issu racial stereotyp relat pain manag',
 'trump scream twitter see poll fox news',
 'trump john kelli got rip apart medal honor recipi video',
 'nra releas fascist ad call trump critic saboteur whose futur failur video',
 'trump take credit releas jfk file bill requir pass year ago',
 'bill maher take trump lie chief staff blister rebuk video',
 'watch report drag sarah huckabe sander brilliant fact check video',
 'swastika cover guy get punch face outsid nazi ralli beauti video',
 'trump get hand british lawmak lie rise crime rate uk',
 'trump brag own origin renoir yet real paint hang chicago galleri',
 'richard spencer fascist goon squad keep florida laugh nazi ass stage',
 'w virginia halloween store boast shockingli racist costum display featur pre obama video',
 'new report prove voter suppress hand trump wisconsin possibl whole elect',
 'watch georg w bush call trump support white supremaci',
 'fake melania trump conspiraci theori take internet storm everyth',
 'trump humili wh walk back attack soldier mom confirm insensit phone call',
 'trump whine like b tch twitter nfl democrat tell go f ck',
 'trump final deliv promis phone call soldier wife say disgust thing ever',
 'god bless whoever photoshop hilari long tie onto donald trump',
 'town defend offici wife n gger rant fb say peopl share post bad',
 'mccain respond zero f ck give trump threat',
 'man stand nation anthem shirt think american flag lawn chair',
 'post flood social media video surfac trump brag hire hot teenag',
 'robert de niro attend chariti event tear motherf er donald trump',
 'satanist brilliantli troll anti gay baker request birthday cake lucif video',
 'fcc rebuk trump refus dismantl first amend petti tantrum',
 'tiffani trump sad hell whole famili complet forgot birthday',
 'watch van jone scorch insan republican think trump chao help agenda',
 'hustler owner fed trump offer mill dirt get impeach',
 'trump administr tri fix dumbest statement yet fail miser imag',
 'whine nfl disrespect trump laugh joke militari ceremoni',
 'white pro trump pastor tri rap attack eminem f cking hilari video',
 'puerto rico governor plead help trump threaten abandon recoveri effort',
 'trump final betray lgbt commun first speech hate group presid',
 'trump made major threat press jake tapper respons perfect video',
 'watch hous dem enough formal start impeach proceed trump',
 'trump threaten shut nbc earli morn hissi fit',
 'white hous confirm resid nazi stephen miller even bigger scumbag knew',
 'fema job deliv food water relief puerto rico',
 'trump ask unqualifi person ever join nafta renegoti team',
 'gop lawmak republican freak dysfunct white hous video',
 'trump explod twitter tantrum prove mental unfit presid',
 'black man beaten nazi pro trump ralli natur cop charg crime',
 'corker last word day care donni path wwiii',
 'penc join trump nfl whinefest leav colt game huff polic brutal protest',
 'missouri senat candid real real subhuman scumbag',
 'watch fox anchor chri wallac rip nra stoog new one lie gun control',
 'outgo gop senat blister adult daycar center trump white hous tweet',
 'one trump fine peopl extradit charlottesvil brutal assault',
 'nazi whine impend releas anti nazi video game video tweet',
 'new low trump exploit la vega shoot rais money campaign tweet',
 'charlottesvil nazi descend upon colleg town anoth torch lit ralli tweet imag',
 'conserv dream come true judg grant rapist joint custodi victim child',
 'trump whine late night host make joke accus conspir democrat',
 'trump buck gop leadership run back arm chuck nanci',
 'internet collect cring photograph snap pic trump nutsack',
 'watch mike penc photo op puerto rico survivor went terribl wrong video',
 'surpris peopl behind fearless girl statu cynic greedi anti feminist men',
 'trump kick hispan heritag month say puerto rico fake accent video',
 'wh staffer explain trump calm storm comment prove potu video',
 'thank trump u economi lost job first time year',
 'slc cop murder cri suspect shoot back taser without even pursu',
 'anti abort republican abort offic',
 'justic depart said legal discrimin transgend peopl',
 'senat bank committe held equifax hear monopoli man show',
 'wake la vega gop final begin support gun control',
 'hilari video show moment berni discov relat snl imperson',
 'trump lose sh twitter media told truth',
 'anti abort republican cheat tri get mistress abort',
 'trump ir decid go give info equifax got hack',
 'trump walk church puerto rico start throw paper towel crowd video',
 'pat robertson say worship trump la vega never would happen',
 'trump puerto rico disgustingli tell puerto rican cost much save',
 'watch trump blame puerto rican recoveri effort problem give',
 'bill reilli write infuri blog post la vega massacr absolut vile',
 'countri guitarist surviv vega shoot chang mind gun control wrong',
 'miami polic union leader join conserv bash nfl la vega massacr',
 'trump mass shoot stop american unit pray peac',
 'geraldo rivera san juan mayor carmen yul n cruz see peopl die video',
 'nra terrorist organ remain silent worst mass shoot american histori',
 'overnight la vega attack deadliest mass shoot american histori detail',
 'trump dedic f king golf trophi peopl suffer puerto rico',
 'er defi trump kneel anthem solidar colin kaepernick video',
 'tea parti superstar get wreck obama n r tweet',
 'watch kamala harri take trump black church scath takedown attack black athlet',
 'nba kowtow racist order player stand anthem',
 'rep joe kennedi torch gop congress screw low incom kid',
 'trump alli curt schill blast horrifi recoveri effort puerto rico video',
 'trump lash puerto rican call ingrat self congratulatori tweet',
 'trump tri shame nfl video hockey fan stand anthem humili',
 'donald trump congratul win elect ask donat puerto rican beg help',
 'trump support tri burn steeler flag hilari figur fire video',
 'obama head disast relief trash trump respons puerto rico tweet',
 'american puerto rico die trump golf tweet',
 'trump throw hissi fit golf cours critic puerto rico respons grow',
 'neo nazi websit lose domain nazi owner lose damn mind',
 'trump incompet handl disast island obama handl one fine',
 'trump hh secretari stole million taxpay unemploy',
 'gop senat smack punchabl alt right nazi internet',
 'trump laugh worri marbl floor die man',
 'new mexico eras actual scienc scienc standard',
 'watch advis wrote trump tax plan say abl buy new car',
 'high school start cave trump punish athlet stand nation anthem',
 'trump press secretari fall apart expos lie obamacar vote video',
 'wound veteran condemn trump use prop attack nfl player',
 'break jare kushner realli woman document prove',
 'watch war veteran john mccain destroy draft dodger trump anthem protest whine',
 'trump embarrass candid lost delet tweet pray forget',
 'trump bad hillari tell presid say',
 'worst possibl person alabama runoff u senat trump fault',
 'loser trump fail miser monday night footbal rate soar',
 'trump furiou ir share info special counsel mueller',
 'one republican senat fed trump retir',
 'four star gener blister trump nfl anthem tantrum put kaepernick',
 'trumpcar offici dead senat collin confirm vote',
 'know live trump love terrorist threaten attack white race video',
 'pittsburgh steeler stand nation anthem speak trump fan hate',
 'democrat take trump woodsh fieri speech defend nfl video',
 'fox news prove trump use fake video tri start war iran',
 'watch gop senat yawn disabl healthcar protest drag away cop',
 'target made major move go blow conserv mind video',
 'republican governor help kill elderli peopl delet messag beg help',
 'peopl upset nfl player disrespect flag constantli accord flag code',
 'billion dollar compani tell employe allow react social media pay cut',
 'zuckerberg person warn russian meddl obama complet blew',
 'racist fascist white supremacist former nfl star chri kluw scorch trump attack athelet',
 'nfl player plan tell trump f today best way possibl',
 'golden state warrior coach wreck trump attack one player',

In [48]:

# apply one hot encoding
onehot_repr = [one_hot(words,voc_size) for words in corpus]
onehot_repr

[[2630, 92, 3031, 1504, 4786, 2423, 305, 3817, 75],
 [2550, 3044, 92, 2302, 4494, 1867, 966, 4609],
 [1266, 2984, 1044, 1830, 2582, 413, 3420, 1297, 2547, 3946],
 [92, 935, 3217, 2853, 1314, 1934, 2420, 2849],
 [723, 2710, 3870, 2630, 92, 2700, 2832],
 [1622, 984, 2232, 4233, 138, 1739, 3789, 3087, 2849],
 [2942, 3832, 3848, 92, 3775, 4862, 4955, 2632, 2080, 3529],
 [92, 3965, 2625, 1622, 3317, 1601, 3414, 4327, 2191, 4031],
 [641, 4267, 2632, 684, 92, 4725, 561, 1711, 3519, 4041, 1022, 2546, 4833],
 [3398, 4363, 4786, 2938, 92, 36, 4808, 269, 4440, 3276, 3365],
 [4991, 1437, 3798, 1585, 2285, 4431, 2982, 157],
 [3398, 2658, 2138, 2872, 2815, 3127, 3818, 4186, 1196, 1305, 1770],
 [2982, 2062, 92, 3997, 2703, 1991, 1702, 4357],
 [3398, 255, 2775, 2066, 2944, 2721, 92, 616, 2693, 3035],
 [1494, 2461, 2043, 3168, 903, 2285, 2815, 1065, 4929, 3792],
 [3316, 4407, 92, 3591, 1599, 1583, 4204, 4991, 3946, 2317],
 [2582, 4233, 4568, 2461, 4786, 92, 1393, 4311, 1286],
 [2712, 4271, 172, 3675, 2630, 92, 2700],
 [4958,
  3077,
  4568,
  1521,
  2248,
  3382,
  2032,
  1217,
  4204,
  4658,
  3856,
  3419,
  1057],
 [4710, 3856, 181, 2508, 4402, 3218, 2712],
 [1074, 1105, 3998, 92, 4305, 3510, 3853, 2641, 1933, 55, 3858],
 [4464, 903, 1770, 1599, 2410, 3847, 2321, 3382, 798, 3805, 1472],
 [3382, 1273, 4833, 2189, 2026, 4087, 1705, 4387, 233, 2475, 984],
 [2231, 3870, 1943, 4250, 984, 3856, 4378, 4303, 2423],
 [759, 4733, 1236, 92, 347, 4867, 812, 2075, 327, 1057],
 [3213, 92, 3519, 4790, 3856, 4372, 84, 1434, 3942, 4833],
 [1521, 2248, 3382, 3856, 1567, 2032, 1217, 3133, 4098, 2382, 1057],
 [3398, 595, 2196, 3870, 130, 4862, 210, 1984, 4609, 92],
 [3278, 1660, 2975, 92, 2032, 1217, 4374, 3362, 1260, 2931, 1057],
 [2768, 2772, 4568, 4658, 4724, 2891, 1802, 4606],
 [2933, 2232, 3163, 181, 2423, 4305, 2877, 842, 4807, 3024, 1472],
 [3398, 1447, 92, 2903, 1103],
 [92, 3905, 727, 3483, 3982, 2711, 1249, 3856, 3416],
 [92, 3127, 92, 4006, 3763, 234],
 [3398, 92, 2524, 874, 611, 2530, 92, 2386, 659, 874, 2453, 3140],
 [3493, 903, 3856, 2746, 3319, 984, 1943, 3856, 2849],
 [4710, 3346, 2018, 750, 560, 1943, 143, 3856],
 [2630, 92, 2750, 580, 447, 674, 1265, 2314, 768],
 [1437, 1273, 4073, 3856, 2538, 4985, 1768, 1802, 2854, 4833],
 [3893, 1824, 3860, 4833, 3502, 4862, 3353, 3190],
 [4862, 822, 434, 2630, 92, 3502, 2944, 2080, 3529],
 [1059, 2191, 4205, 3077, 4958, 3811, 2503, 92, 3127, 2492, 3117, 1057],
 [3998, 2042, 2609, 92, 1974, 357, 2455, 3430, 3510, 47, 92],
 [92, 1569, 213, 2986, 2703, 4862, 494, 3529, 2813, 4609],
 [3398, 1584, 1852, 894, 2986, 2511, 1673, 1056, 812, 4018, 1057],
 [759, 4733, 2762, 3168, 2986, 4402, 2503],
 [2933, 894, 2986, 2250, 417, 2712, 92],
 [92, 181, 3216, 172, 4975, 4945, 759, 1778, 2362],
 [3077, 1434, 36, 2380, 327, 2353, 3638, 47, 1974],
 [4034, 2137, 1578, 92, 150, 4204, 2153, 1057],
 [3903, 857, 3218, 2712, 4327, 964, 3462, 4971, 1699, 3490, 2197],
 [92, 3031, 2830, 4303, 4833, 248, 168, 4204, 1470, 4700, 2767, 4635],
 [2006, 47, 1286, 1521, 4175, 2423, 4847, 3805],
 [92, 978, 4460, 4460, 4031, 1236, 1199, 1223, 4833, 4942],
 [92, 4601, 3027, 2362, 759, 1778, 4389, 1345],
 [1602, 718, 2939, 3853, 765, 903, 3446, 3502, 2849],
 [1943, 3990, 92, 4804, 172, 4975, 3502, 2625, 2538, 2593],
 [92, 2771, 894, 138, 2547, 3156, 4496, 1482, 4502],
 [92, 2524, 1924, 3549, 222, 3725, 3410, 4968, 157, 4833],
 [3443, 3761, 2006, 1934, 4337, 92, 3870, 3466, 2502, 4604, 1057],
 [2938, 92, 1660, 2604, 597, 2853, 4374, 3276, 92, 850, 999],
 [838, 4441, 2231, 2196, 2576, 2499, 4382, 2609, 2032, 1217, 3866, 1057],
 [641, 2853, 55, 2503, 2975, 92, 2903, 4786, 741, 4833],
 [4031, 3832, 766, 92, 1991, 1397, 1286, 2455],
 [3883, 3490, 47, 92, 4524, 4320, 1521, 2248, 3382, 4929],
 [268, 2336, 4710, 1378, 4627, 1738, 1631],
 [92, 3645, 774, 1991, 2126, 3363, 3234, 644, 599],
 [2231, 746, 92, 3502, 2982, 3483, 3140, 4833],
 [1602, 718, 181, 4223, 4563, 4303, 812, 3870, 92, 2703],
 [4303, 812, 4235, 92, 2703, 3051],
 [4367, 4320, 2719, 2853, 3502, 2751, 4460, 3231, 850, 1022, 1276],
 [2511, 3648, 2625, 987, 2862, 1469, 1437, 1273, 3526],
 [1996, 903, 3757, 2279, 4087, 1705, 4159, 2779, 2032, 1217, 3856, 3419, 1057],
 [3398, 1585, 984, 2232, 2872, 66, 2032, 1217, 4817, 1885, 4219, 1793],
 [4786, 783, 4303, 1363, 2453, 1867, 822, 1626, 1934, 1314],
 [595, 2062, 3118, 923, 4966, 948, 4139, 802, 4789],
 [3398, 4692, 4459, 2503, 92, 1937, 4031, 560, 1217],
 [1978, 812, 1062, 3899, 4320, 2032, 1217, 4073, 798, 3805, 2447],
 [92, 3346, 1551, 1440, 3585, 2066, 3216],
 [92, 2284, 2062, 2159, 2772, 102, 1428, 2585, 181, 3599, 987],
 [2759, 3076, 2231, 92, 432],
 [3979, 3645, 2767, 4863, 1033, 2135, 1421, 4710, 971],
 [903, 3856, 2247, 1148, 849, 2066, 2641, 2032, 1217, 2630, 92, 1057],
 [2630, 92, 434, 4226, 738, 1447],
 [92, 3025, 988, 1097, 418, 4786, 3651, 4790, 1389, 497],
 [1926, 2286, 1590, 3536, 3131, 4628, 4796, 925, 768, 3778],
 [4786, 1521, 857, 3025, 2032, 1217, 3118, 950, 1057],
 [2032, 1217, 494, 2547, 2711, 2944, 181, 2975, 3793, 4833],
 [92, 3732, 3041, 3856, 2853, 1703, 2753, 3217, 1160, 1973],
 [2582, 588, 2952, 3536, 2362, 3870, 92, 2891],
 [1199, 1996, 903, 1599, 181, 1725, 4233, 1152, 1590, 1770, 4327],
 [4303, 92, 4568, 2455, 2401, 1253, 2612, 4347, 4031, 4191],
 [3398, 2327, 611, 4877, 92, 4681, 1440, 2653, 903, 4929, 3240],
 [2759, 1266, 3420, 4194, 4286, 3547, 1199, 92, 2573, 2355],
 [3398, 1005, 92, 4460, 3775, 595, 2196, 1363, 2250, 2698, 1705, 339],
 [2032, 1217, 2524, 4710, 4204, 3870, 3171],
 [4935, 92, 2872, 2738, 2853, 4648, 2986, 1705, 644, 599],
 [2423, 4847, 4833, 2630, 92, 2380, 2815, 1353, 3480, 2032, 1217],
 [3617, 92, 4854, 2225, 1780, 1626, 1083, 759, 4733, 515],
 [92, 2580, 902, 2767, 3870, 1212, 4354, 4226, 1212, 3585, 674],
 [3398, 4034, 1314, 4223, 92, 4564, 3035, 3077],
 [1725, 3998, 4256, 2609, 92, 379, 1989, 3942, 1867, 1274],
 [3480, 903, 1770, 1599, 1954, 2623, 2772, 2986, 533, 2709, 4043, 199],
 [2032, 1217, 641, 1851, 213, 1022, 3468, 4752, 3805],
 [3398, 3645, 4627, 3798, 1945, 2524, 3634, 1033, 3137],
 [3979, 3645, 2767, 4320, 560, 903, 1567, 2032, 1217],
 [92, 2939, 1975, 2635, 2588, 3133, 4098, 2785, 442, 2732, 1867, 1531],
 [4847, 4842, 1535, 4833, 3419, 3735, 999, 2527, 2814, 1148],
 [1602, 718, 3965, 2248, 3382, 3021, 1315, 1057],
 [1415, 1631, 3362, 128, 2455, 2547, 2470],
 [984, 4710, 4320, 725, 2604, 4126],
 [903, 3856, 1567, 4986, 4227, 2248, 3382],
 [3856, 1943, 4127, 983, 442, 903, 4031, 1496, 92, 1429],
 [1944, 4047, 2759, 1660, 2996, 4994, 1808, 4217, 2815, 2130, 3131],
 [1602, 718, 2688, 3835, 297, 2465, 3027, 4712, 2331, 92, 618, 1272],
 [1223, 327, 1780, 92, 4402, 172, 4975, 1908, 3570, 4357],
 [3398, 3487, 2832, 4347, 92, 2503, 2026, 1726, 1860],
 [92, 2376, 4235, 2789, 47, 2939, 4221, 3366, 2588],
 [207, 954, 92, 4072, 172, 4975, 47, 3027],
 [92, 1485, 1497, 582, 3048, 1271, 2580, 1712, 2813, 4137, 324],
 [92, 2768, 812, 1062, 890, 2538, 1520, 248, 4954, 2789, 47],
 [92, 1711, 3870, 4404, 4700, 3455, 1057],
 [3617, 92, 108, 2547, 1022, 2394, 3000, 1489, 4226],
 [1642, 2759, 954, 1774, 2388, 494, 92, 4710, 2456],
 [92, 2772, 3276, 2702, 3990, 1970, 111, 2547, 3647],
 [2107, 2191, 857, 3028, 3028, 3234, 4596],
 [595, 2062, 3905, 4703, 1170, 270, 1126, 4867, 2630, 92],
 [92, 1780, 968, 456, 644, 213, 1942, 4226, 4700],
 [2547, 3979, 619, 2388, 3998, 4169, 936, 181, 1670],
 [683, 2759, 3718, 4455, 4235, 3634, 1874, 447, 4494, 80],
 [1867, 1272, 2813, 546, 2630, 92, 2768, 2321, 4174, 96, 383, 2205],
 [3398, 4710, 971, 4946, 2986, 1824, 4990, 533, 795],
 [3493, 2772, 1326, 1994, 1594, 2538, 3405, 4954],
 [3856, 2784, 2219, 1105, 903, 1851, 1705, 1170],
 [3749, 269, 3510, 4601, 92, 2771, 3856, 2130, 3131],
 [2547, 674, 2759, 2130, 3131, 92, 2026, 958, 1622],
 [92, 1843, 2478, 4606, 2609, 3168, 2139, 3703, 570],
 [4282, 3159, 92, 546, 3346, 1551, 1440, 2548, 485, 2453, 2712],
 [641, 4938, 2703, 2712, 447, 1807, 92, 2455],
 [903, 971, 2443, 853, 795, 1705, 2237, 829, 2853, 2593, 1057],
 [1988, 312, 1249, 1422, 92, 3168],
 [92, 4073, 3121, 4018, 972, 1272, 4387, 4137, 1429],
 [4654, 4367, 92, 4235, 3870, 4174, 1033, 4139, 16, 2751, 2478],
 [1530, 4753, 1152, 36, 4991, 1437, 181, 1434, 3385, 3634],
 [4842, 1535, 181, 233, 4699, 4327, 3135, 3932, 1411, 2415, 1810, 1057],
 [3883, 3035, 903, 4523, 1569, 2388, 2335],
 [1705, 4366, 1631, 2630, 92, 2762, 1631, 2538, 4268, 1472],
 [3893, 1824, 3860, 1065, 4069, 4303, 2653, 4503, 1010],
 [92, 191, 1909, 4246, 3231, 1033, 2135, 2625],
 [4124, 2359, 4869, 2814, 1867, 7, 4419],
 [1463, 4627, 759, 4733, 1363, 181, 1978, 923, 4833, 1363, 171, 293, 3455],
 [4991, 1437, 3502, 4753, 4378, 4057, 1470, 3030, 4259, 4204, 2006, 1681],
 [92, 730, 2773, 4137, 2883, 3803, 66, 4290, 298],
 [157, 2824, 1617, 92, 2501, 3930, 92, 2658, 494],
 [641, 1701, 1521, 92, 4041, 4558, 3932, 4303, 456, 2163],
 [92, 2939, 3462, 4971, 2588, 2712, 485],
 [1867, 1978, 76, 3979, 4206, 4416, 58, 1832],
 [361, 1741, 1268, 92, 3305, 3803, 3502],
 [3398, 903, 3856, 3946, 2118, 2006, 4593, 614, 485, 1386, 1057],
 [3398, 92, 3881, 802, 1437, 476, 1569, 2949, 84, 248, 3481],
 [4450, 2635, 4219, 92, 1272, 4946, 966, 3036],
 [3398, 718, 4204, 1470, 248, 4416, 1286, 1291, 3786, 2593],
 [3013, 2848, 2255, 3925, 938, 4822, 1057],
 [718, 4833, 1022, 3948, 4031, 92],
 [1470, 3030, 1820, 1977, 4367, 92],
 [4319,
  3117,
  2658,
  494,
  3487,
  2885,
  1813,
  4319,
  1513,
  1867,
  966,
  3638,
  4833,
  1057],
 [595, 2062, 3309, 2062, 1984, 715, 128, 485, 92, 584, 1646],
 [1622, 2444, 750, 2724, 759, 759, 3036, 3906],
 [1273, 3362, 2580, 2423, 494, 2630, 92],
 [2205, 92, 3163, 3610, 485, 2712, 447, 1802, 4804, 2931],
 [1378, 92, 4485, 660, 2712, 298, 2455, 3391],
 [3994, 1770, 4671, 730, 1991, 4357, 2551, 92, 723],
 [4416, 3077, 65, 595, 2196, 2625, 935, 3754, 1057],
 [2582, 4223, 460, 255, 2687, 1836, 4041, 143, 4593, 1934],
 [4484, 92, 2762, 2712, 4609, 3159],
 [4416, 1291, 2101, 819, 485, 2006, 92, 4804, 4048, 2548, 2355],
 [2538, 3118, 4628, 92, 302, 3420, 1212, 2355],
 [850, 2931, 4899, 92, 2832, 2849],
 [2933, 4378, 3929, 1186, 2712, 2455, 4609],
 [92, 92, 3579, 4149, 3883, 1590, 191, 3022, 1342, 172, 4975],
 [3398, 641, 759, 4733, 1974, 3519, 718, 4416, 1291, 3714],
 [92, 3159, 4327, 555, 2455, 4836],
 [1774, 3856, 3958, 1870, 4621, 4242, 2492, 1057],
 [3119, 684, 4466, 1788, 4990, 2423, 4558, 2921, 2891],
 [92, 3025, 3118, 2509, 1290, 1187],
 [1437, 1439, 312, 1820, 3817, 4416, 92, 2456, 4833],
 [1270, 2976, 1780, 4993, 2688, 1083, 927, 3490, 1996, 4800],
 [92, 1652, 2512, 3231, 2614, 2503, 2423, 4847, 3805, 3470, 4569, 2164],
 [1463, 4627, 92, 3815, 4204, 1470, 1122, 2751, 3870, 3634],
 [3398, 4401, 357, 3022, 3966, 1010, 2931, 4256, 92, 3930, 4833],
 [1187, 92, 3450, 3137, 3133, 3946, 1780, 138, 2144, 839],
 [92, 2751, 4410, 2193, 2291, 2291, 254, 759, 4733, 564, 802],
 [903, 3856, 1567, 1991, 2144, 674, 1933, 55, 619, 3995],
 [3398, 1437, 1273, 4568, 1286, 3160, 1092, 4267, 4296],
 [3399, 1732, 3163, 2200, 1631, 4881, 3217, 92, 3870, 491, 4606],
 [1033, 874, 3375, 3729, 4894, 4496, 385, 1152, 3386, 1646],
 [92, 894, 2538, 1788, 1371, 595, 2062],
 [92, 1437, 476, 3025, 1441, 1456, 3153, 3443, 109, 1057],
 [3510, 4559, 94, 36, 3870, 92, 3647, 4969, 4311, 1481, 2145, 1057],
 [92, 2503, 4626, 4559, 358, 1186, 3792, 4249, 2108, 2423, 2197],
 [3792, 1346, 2503, 92, 2703, 3881, 802, 746, 1105, 1057],
 [3398, 1363, 2508, 3893, 1824, 3860, 1010, 2250, 2476, 1057],
 [4152, 128, 1447, 181, 997, 2548, 323, 3634, 4374, 1888, 1057],
 [92, 181, 418, 3002, 971, 2703, 3617, 3036, 2315, 186],
 [92, 3044, 545, 2464, 2521, 1774, 4596, 4596, 1710, 1144, 2038],
 [559, 4806, 94, 3281, 75, 66, 3943, 2580, 3634, 3296, 3853],
 [1797, 2789, 2687, 4477, 3083, 10, 1622, 1836, 1594, 4808, 4859, 2853, 1057],
 [4786, 1363, 2609, 327, 1471, 418, 92, 4795, 1260, 2903, 47],
 [3398, 4743, 1797, 841, 3870, 92, 2524, 759, 1389],
 [923, 1187, 92, 987, 2862, 2503, 2582, 1278, 3645],
 [92, 4235, 1973, 816, 4031, 3502, 3399, 4466, 857, 1732, 3185, 3870],
 [92, 821, 1022, 4043, 317, 2538, 4753, 1943, 1780, 4402, 172, 4975],
 [92, 3163, 2784, 4715, 3185, 3870, 3399, 4628, 1991, 4227, 4938, 2455],
 [619, 4394, 3782, 432, 3077, 2834, 4109, 1507, 2630, 92],
 [601, 4320, 1974, 4628, 381, 3296, 2593, 570, 1991, 2547, 4988, 351, 2982],
 [1273, 1306, 4318, 172, 4975, 3990, 92, 4501],
 [1590, 326, 3346, 3673, 4224, 2949, 2006, 4593, 179, 198],
 [351, 3026, 4363, 2944, 1057, 3, 92, 3044, 4016, 1148, 4752],
 [3218, 1268, 1318, 2210, 3165, 938, 801, 4061, 1265, 2630, 92],
 [1779, 2390, 2975, 1199, 1996, 1857, 4167, 1820, 4725, 2653, 1057],
 [709, 1105, 92, 2979, 2518, 4378, 4057, 2030, 903],
 [2889, 92, 4509, 3117, 2903, 4186, 3905, 2374, 1820],
 [3398, 2134, 1705, 897, 2625, 4710, 2949, 92, 1926, 533, 3496],
 [2912, 3547, 2696, 92, 4785, 3519, 1761, 181, 3754],
 [92, 1429, 2772, 4584, 4250, 1885, 1774, 629, 2854, 2849],
 [821, 4753, 370, 92, 2580, 413, 47, 4684],
 [759, 2938, 92, 1978, 2772, 4378, 3502, 1418, 172, 802, 3077, 1057],
 [92, 3579, 3076, 2564, 533, 92, 3420, 2484, 321, 2699],
 [92, 3163, 3451, 1566, 2635, 4378, 2832, 839, 1660, 1286],
 [92, 1631, 4628, 4501, 2738, 290, 2623, 2026, 312, 1057],
 [3398, 4733, 4422, 2746, 843, 4494, 3754, 1978, 92],
 [92, 3420, 298, 4551, 1951, 4942, 3469, 606],
 [759, 4733, 857, 3050, 3634, 4140, 2611, 3217, 2480, 200, 213],
 [213, 3140, 2784, 1963, 2612, 978, 92, 3579],
 [92, 494, 1118, 1970, 2455, 1407, 2065, 2814, 2453],
 [903, 971, 4710, 2470, 2246, 759, 4733, 1057],
 [92, 750, 2538, 903, 2609, 208, 2903, 1286],
 [138, 1590, 644, 3634, 2938, 92, 4374, 4862, 2232, 3929, 3036],
 [2291, 2465, 3035, 4954, 3127, 1005, 4721, 3678],
 [1535, 1407, 92, 4753, 4236, 1838, 1542, 3682, 3199, 3718, 4233, 4242],
 [4133, 3856, 1567, 4596, 4596, 4357, 200],
 [3398, 595, 937, 3864, 4459, 1441, 3510, 1541, 4786, 1705, 2703, 925, 959],
 [3069, 903, 3856, 746, 1826, 564, 1604, 92, 759, 4733, 4833],
 [1705, 92, 198, 2547, 1175, 2276, 4233, 2135],
 [3634, 821, 2350, 4559, 1199, 3634, 1057, 3682, 1057, 4833],
 [4786, 1504, 92, 4992, 1177, 3274, 3131, 688, 3942, 1434, 4833],
 [2276, 3634, 4580, 1371, 428, 601, 3856, 4347, 4603, 4374, 4833, 2849],
 [3979, 1404, 2741, 945, 3119, 4593, 4280, 2759, 4077, 3998, 2248],
 [92, 821, 2490, 3027, 2196, 3276, 413, 1521, 3842, 1943],
 [92, 3395, 903, 3314, 2935, 4031, 386, 361, 3050],
 [2582, 1250, 4514, 55, 520, 4057, 92, 348],
 [3398, 4842, 1535, 3446, 18, 92, 3579, 4651, 1843, 4968, 248, 1057],
 [2115, 2547, 442, 4269, 3805, 2337, 649, 1710, 1199, 1142, 4352],
 [92, 4455, 3043, 3451, 1411, 1991, 92, 3579, 923, 940, 1057],
 [1973, 2302, 4146, 92, 779, 1278, 4559, 2609, 872, 1057],
 [626, 92, 143, 795, 1179, 3140, 4378, 4303, 2423],
 [794, 2232, 674, 4881, 105, 3131, 4031, 751, 1730, 3217, 867],
 [1199, 853, 4710, 853, 4327],
 [1485, 2809, 3965, 4450, 1725, 2573, 2547],
 [3856, 1274, 2018, 2207, 4916, 1340, 3738, 1590, 2380],
 [2771, 1177, 3274, 903, 3163, 3272, 2524, 925, 959],
 [3077, 1057, 2380, 2607, 172, 4346, 1152, 4958, 3332],
 [92, 4204, 1470, 2538, 2944, 2872, 2653],
 [1199, 853, 4710, 1574, 2772, 181, 2400, 853],
 [92, 2443, 4385, 4402, 3990, 111, 4916, 3025, 1959],
 [92, 816, 4796, 92, 3579, 4494, 2939, 1994, 4187, 3764, 1057],
 [2756, 314, 1991, 3346, 92, 1177, 3274, 644, 4372, 599],
 [92, 92, 3579, 936, 1780, 92, 3412, 934, 269, 3396],
 [3398, 92, 3305, 92, 3412, 321, 2699, 3842, 3990],
 [3792, 1497, 3877, 1422, 1526, 351, 1177, 3274, 4047, 3810, 2666],
 [4226, 2624, 2181, 3274, 3131, 3848, 2153, 925, 959, 248],
 [486, 3718, 488, 2767, 1407, 3979, 13, 4753, 1177, 3274, 4047],
 [92, 2130, 3131, 3231, 2006, 467, 4737, 2711],
 [537, 280, 4797, 1290, 1001, 2730, 2333, 381, 2035, 1788, 2547, 2317, 1057],
 [3510, 3803, 1143, 1738, 2089, 4673, 2130, 3131, 2006, 950],
 [4379, 1177, 3274, 3502, 4217, 2130, 3131, 2006, 950, 1472],
 [92, 1331, 172, 3844, 3832, 570, 2547, 956, 92, 3579],
 [1265, 2995, 92, 4894, 3673, 4920, 2534, 1775, 1057],
 [4327, 2641, 65, 181, 4223, 2853, 381, 4849, 4833],
 [3398, 2692, 222, 2503, 92, 138, 4796, 2219, 4870, 3502, 138, 3553],
 [928, 1276, 1622, 4230, 1139, 326, 3673],
 [1599, 4034, 3104, 4347, 903, 1626, 727, 1504, 1755, 2144],
 [92, 302, 876, 1864, 3571, 1005, 321, 2699, 92, 3579, 1057],
 [92, 3775, 92, 3412, 3870, 4590, 573, 593, 4833],
 [92, 2772, 4867, 4753, 1057, 4260, 4460, 326, 3673, 4235],
 [2630, 92, 4012, 4387, 47, 494, 3319, 92, 3412, 1845, 533],
 [92, 2524, 2772, 1810, 3712, 4593, 3077, 2285, 660, 1057],
 [2853, 2444, 1694, 978, 2066, 92, 2026, 92, 3579, 4833],
 [2006, 92, 3579, 2317, 92, 3832, 4833],
 [92, 2939, 3469, 606, 3832, 3848, 3647, 92, 3579, 2026, 651],
 [4352, 3634, 2420, 4204, 2012, 3634, 3547, 4204, 2281, 2153],
 [92, 1315, 292, 1694, 4515, 2853, 292, 1705, 198],
 [92, 369, 1909, 1477, 2795, 2258, 3919],
 [903, 3856, 350, 3340, 1463, 4627, 3634, 2582],
 [92, 2580, 1161, 393, 1508, 2317, 1590],
 [4786, 4231, 3663, 2453, 2422, 2422, 2110],
 [3398, 1440, 582, 92, 4929, 1768, 1991, 889, 3054, 4786, 2492],
 [1885, 4219, 4494, 3752, 92, 972, 3553, 326, 3346, 3673],
 [92, 2738, 1909, 1027, 1456, 4340, 2703, 4357, 2688, 1057],
 [3489, 356, 1945, 92, 2604, 1568, 3502, 4753, 1139],
 [2933, 3462, 4971, 150, 1271, 4256, 2609],
 [3398, 3455, 356, 1437, 1273, 434, 4267, 2493, 92, 3673, 4242, 821],
 [92, 1504, 1567, 1179, 1996, 4833, 4737, 2693],
 [92, 2982, 4416, 1780, 1286, 1991],
 [4673, 1260, 1970, 984, 3008, 143, 3856, 92, 723],
 [3683, 92, 629, 2854, 3925, 3027, 2821, 2315, 362],
 [92, 2456, 2443, 4988, 111, 233, 567, 2712],
 [1705, 4710, 3856, 2696, 92, 1585],
 [4754, 2682, 4405, 746, 92, 4753, 3673, 903, 988, 1775],
 [1649, 1974, 1445, 3856, 2344, 857, 2688],
 [3168, 1196, 92, 1236, 3803, 3420, 3502, 759, 3419, 1057],
 [3255, 3712, 326, 3346, 3673, 2200, 92, 4460, 839],
 [1943, 2503, 92, 1937, 2062, 2832, 4320, 4753, 1057],
 [595, 2062, 2609, 92, 2604, 923, 1057, 2772, 4494, 3455, 2895],
 [3398, 903, 3856, 4427, 564, 2474, 4242, 2508, 4817, 2232],
 [3732, 1631, 4628, 4485, 4402, 360, 3979, 2153, 1057],
 [4710, 3076, 533, 1122, 868, 2547, 1996, 3817, 1845, 533],
 [2547, 2530, 4753, 1139, 370, 4593, 159, 4111, 4593, 1934],
 [1182, 3029, 3022, 1780, 4740, 1277, 3024, 4363, 2944, 96, 3240],
 [1157, 1970, 528, 1867, 1531, 2853, 3905, 2935],
 [1622, 94, 759, 1778, 641, 4753, 2682, 3864, 4126, 897, 92, 3502, 4077],
 [4753, 1139, 1768, 1780, 92, 172, 234, 3362, 2931, 1260],
 [1346, 1770, 792, 1127, 4223, 92, 3502, 1705, 1139],
 [3398, 92, 4580, 802, 3501, 2404, 1991, 4753, 1139, 4627, 2642, 2832],
 [92, 2855, 3455, 4753, 1951, 4942, 2538, 1705],
 [92, 3420, 674, 2795, 2547, 3035, 3892],
 [641, 2632, 3346, 1975, 1991, 2455, 2493, 1830, 1134, 92, 4387],
 [2534, 1775, 3880, 660, 4031, 92, 3870, 2753, 4043, 317],
 [3398, 3792, 1346, 3077, 4146, 92, 959, 2703, 2138, 361, 3050],
 [92, 3276, 991, 1249, 4357, 584, 3217, 903, 2108, 84],
 [92, 1140, 1437, 1273, 2979, 4486, 2474, 2795, 2006],
 [92, 821, 2944, 4635, 3764, 984, 2231, 3276, 1978],
 [4710, 3856, 1471, 601, 4311, 1569, 903, 4357, 1702, 629, 4833],
 [1003, 1694, 2668, 812, 3286, 2380, 1053, 233, 4001, 4568, 1057],
 [2267, 2853, 3366, 1982, 92, 1730, 2455, 4363, 1314],
 [2933,
  1437,
  1273,
  2933,
  3362,
  3856,
  1712,
  2688,
  2775,
  2020,
  2866,
  3792,
  1057],
 [3570, 2632, 1770, 4894, 2759, 1885, 684, 903, 77, 3792],
 [92, 369, 802, 2547, 2247, 3835, 2515, 659, 4929, 3029, 3831],
 [92, 1352, 4485, 4291, 1996, 4710, 2474, 1305, 1378, 4627],
 [2712, 2547, 4167, 2455, 4609, 4402, 434, 92, 1472],
 [2206, 340, 3022, 58, 1895, 4174, 2612, 3634, 1057],
 [1199, 2905, 903, 3943, 971, 2247, 2905, 2538],
 [3282, 4255, 3870, 447, 23, 75, 1122, 706, 3176, 1553],
 [2853, 1631, 2336, 1885, 92, 2205, 1702, 4357, 1057],
 [3398, 4295, 3466, 2604, 1010, 2270, 2237, 3339, 4146, 3930, 2455, 3638],
 [92, 4854, 2225, 2573, 1438, 211, 4694, 1768, 3883],
 [92, 3729, 2546, 4242, 3502, 4118, 2168, 2548],
 [3298, 256, 4235, 92, 4946, 4700, 2767, 1236, 3645, 3965, 467, 3346],
 [92, 4725, 2832, 1848, 4968, 2548, 4250, 3586],

In [49]:
#  then pass to Embedding Representation
sent_length = 20

embedded_docs=pad_sequences(onehot_repr, padding = 'pre', maxlen = sent_length)
embedded_docs

array([[   0,    0,    0, ...,  305, 3817,   75],
       [   0,    0,    0, ..., 1867,  966, 4609],
       [   0,    0,    0, ..., 1297, 2547, 3946],
       ...,
       [   0,    0,    0, ..., 3502, 4093, 3208],
       [   0,    0,    0, ..., 2250, 1750, 1728],
       [   0,    0,    0, ...,  854, 4786, 3118]], dtype=int32)

In [56]:
# create model
Embedding_vector_features = 40
model = Sequential()
model.add(Embedding(voc_size, Embedding_vector_features, input_shape=(sent_length,)))
model.add(Bidirectional(LSTM(100)))
model.add(Dense(1, activation = 'sigmoid'))
model.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics = ['accuracy'])
print(model.summary())

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/embedding.py:103: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_6 (Embedding)         │ (None, 20, 40)         │       200,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_4 (Bidirectional) │ (None, 200)            │       112,800 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │           201 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 313,001 (1.19 MB)

 Trainable params: 313,001 (1.19 MB)

 Non-trainable params: 0 (0.00 B)

None

In [57]:
import numpy as np
x_final = np.array(embedded_docs)
y_final = np.array(y)

In [58]:
# train test split
from sklearn.model_selection import train_test_split
x_train , x_test , y_train ,y_test = train_test_split(x_final , y_final , test_size = 0.33,random_state = 42)

In [59]:
#model trainning
model.fit(x_train ,y_train , validation_data = (x_test , y_test),epochs = 10 ,batch_size = 32)

Epoch 1/10
893/893 ━━━━━━━━━━━━━━━━━━━━ 14s 10ms/step - accuracy: 0.9159 - loss: 0.2075 - val_accuracy: 0.9351 - val_loss: 0.1645
Epoch 2/10
893/893 ━━━━━━━━━━━━━━━━━━━━ 9s 10ms/step - accuracy: 0.9546 - loss: 0.1172 - val_accuracy: 0.9366 - val_loss: 0.1658
Epoch 3/10
893/893 ━━━━━━━━━━━━━━━━━━━━ 9s 10ms/step - accuracy: 0.9691 - loss: 0.0847 - val_accuracy: 0.9366 - val_loss: 0.1722
Epoch 4/10
893/893 ━━━━━━━━━━━━━━━━━━━━ 9s 10ms/step - accuracy: 0.9768 - loss: 0.0639 - val_accuracy: 0.9341 - val_loss: 0.1796
Epoch 5/10
893/893 ━━━━━━━━━━━━━━━━━━━━ 9s 9ms/step - accuracy: 0.9831 - loss: 0.0496 - val_accuracy: 0.9358 - val_loss: 0.2076
Epoch 6/10
893/893 ━━━━━━━━━━━━━━━━━━━━ 9s 10ms/step - accuracy: 0.9883 - loss: 0.0362 - val_accuracy: 0.9315 - val_loss: 0.2497
Epoch 7/10
893/893 ━━━━━━━━━━━━━━━━━━━━ 9s 10ms/step - accuracy: 0.9907 - loss: 0.0277 - val_accuracy: 0.9363 - val_loss: 0.2632
Epoch 8/10
893/893 ━━━━━━━━━━━━━━━━━━━━ 10s 10ms/step - accuracy: 0.9940 - loss: 0.0191 - val_accuracy: 0.9366 - val_loss: 0.3290
Epoch 9/10
893/893 ━━━━━━━━━━━━━━━━━━━━ 8s 9ms/step - accuracy: 0.9951 - loss: 0.0148 - val_accuracy: 0.9378 - val_loss: 0.3091
Epoch 10/10
893/893 ━━━━━━━━━━━━━━━━━━━━ 11s 10ms/step - accuracy: 0.9955 - loss: 0.0131 - val_accuracy: 0.9342 - val_loss: 0.3039

In [60]:
y_pred = model.predict(x_test)

440/440 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step

In [61]:
import numpy as np
y_pred = np.where(y_pred>=0.5 , 1,0)

In [62]:
from sklearn.metrics import confusion_matrix, accuracy_score
confusion_matrix(y_test , y_pred)

array([[7259,  520],
       [ 406, 5888]])

In [63]:
print(accuracy_score(y_test , y_pred))

0.934200241597385